mediamicroservices/mm

ingestfile, makeresourcespace, mmfunctions
Added a preservation mode so that digitized materials can be packaged
using ingestfile and delivered using a specified directory.
=> added preservation mode

makeprores
changed prores profile from standard to HQ
=> change prores profile to HQ

checksumpackage
stopped excess versioning/enabled relative paths for input
=> Modify checksumpackage

checksumpackage
Reports on added and deleted files (still has a few quirks)
=> Checksumpackage mismatch options

mmconfig
Running GUI now does not erase previous configurations.  Typo in commit history-still doesn’t incorporate fixity DB options
=> Changed GUI to read from config file

mm-desktop-setup
=> mm-desktop-setup: initial commit

ingestfile, migratefiles
Ingest file will now not erase files if   OUTDIR_INGESTFILE is set to same directory as AIP_STORAGE in mmconfig
=> fixed ingestfile bug

checksumpackage
Eliminated package path being set outside the loop for checksum package.
=> fixed broken loop

mmconfig
- "modern" shebang
- $(...) preferred over \`...\`
- = preferred over == inside [[...]]
=> housekeeping

mmfunctions
- typos
- tried to uniform indent to 4, and spacing
- = preferred over == in [[...]]
- uniformed 2>/dev/null preferred over 2> /dev/null
- uniformed space before ; then and ; do
- uniformed space before ;;
- $(...) preferred over \`...\`
I personally prefer to include the shebang also in scripts which are executed only by other scripts, because it remembers me the programming language used.
=> housekeeping (2nd attempt)

mmfunctions
Hopefully this will fix https://github.com/mediamicroservices/mm/issues/102...
=> Address db event outcome reporting

mmfunctions
=> fixed bugs with operator reporting to DB

verifytree
Now works with current CUNY package structures, warnings have been cleaned up and prettified.
=> Adjusted verifytree

verifytree
Improves reporting, allows for slates and captions.
=> More verifytree additions

makeyoutube, mmfunctions
I think this is doing what we want it to at this point...
=> Transition to loudnorm

makemkvchapters
Creates ordered chapters in a matroska file
=> makemkvchapters

mmfunctions
=> change conditionals to favor normalization

mmfunctions
goes along with https://github.com/amiaopensource/ltopers/pull/59
=> remove ltoperconfig functions

ingestfile
Adds option in GUI to perform interlacement test.  If option not selected there is no test or subsequent prompt.
=> Modify ingestfile gui

mmfunctions
Less aggressive approach to escaping is required.
=> save the umlauts!!!

mmfunctions
this should make this more reliable for opening the sql database
=> change bind address

mmfunctions
Report will try twice to access DB before dumping commands to desktop.
Command dump email function added.
=> DB error enhancements

ingestfile
This should resolve https://github.com/mediamicroservices/mm/issues/117 using the comparison of modification time to current time.
=> add check for modification

makeframemd5
Adds a script modeled after makemetadata for creating frame md5s of package source material
=> create makeframemd5 script

createpremisdb
add indexes to db creation to speed up searchlto
=> add spaces and indexes

searchfingerprint
Adds a script to generate fingerprints from input videos and compare against mm database for potential content matches.
=> Add searchfingerprint

mmfunctions
Perhaps this resolves https://github.com/mediamicroservices/mm/issues/151.
=> delete `unset DEPENDENCIES`

ingestfile
=> This seems like a fix the variable problem?

mmconfig, mmfunctions
Helpful for users that want a different .md5 file than that currently specified in writelto
=> added in option for LTO_MD5_FLAGS

mmfunctions
resolves https://github.com/mediamicroservices/mm/issues/172
=> replace `$OSTYPE` with `uname -s`

mmfunctions
necessary to work with writelto
=> added in _check_for_lto_index_dir function

mmfunctions
Used in https://github.com/mediamicroservices/mm/blob/master/mmfunctions#L459
=> add missing option

mmconfig
- `${VERSION}` is not set
- `-b` is not used
=> delete unused option and undefined value

makelossless
Changed this so that the output of the lossless files is Matroska instead of Quicktime.
=> Changed makelossless to output to Matroska

mmtest
=> warning about version mismatch

ingestfile
WIP - includes two functions that are currently pretty local to CUNY, but skips them if you don’t drag in digitization logs. To expand upon!
=> Ingestfile audio mode

ingestfile
No more years-long audio files
=> Fix variable typo + print leading zeros

ingestfile
Removed black frame test, phase check test and delivery to IA from
preservation mode.
=>  Removed tests and moved _reset directory

mmfunctions
For clarity and avoiding endless loops
=> Camera process changes

verifypackage
- use modern shebang
- cut description to 80 chars
- delete not necessary commands (`unset` and `;`)
- alignment
=> small stylistic changes

makederiv, mmfunctions
Option to only use first audio track (even if its mono) in makederiv
=> Created audio option to only consider first track

verifypackage
Fixed added space between force and -fx.
=> added space to force option

makederiv
now full frame and datarate controlled by crf
=> update method to make podcasts

README.md
=> Patch commands in code view

tesseract.conf
This makes the text output of the PDF more readable
=> Add interword spaces

tesseract.conf
=> delete unneeded digit

makederiv
=> Adds audio filter if the audio frame rate is variable

finishpackage
Added more derivatives to finishpackage.
=> Morederivs

README.md
updated documentation by adding descriptions and command examples to new microservice entries.
=> Added microservice descriptions and commands to documentation 

mmfunctions
Changed timecode font from 24 to 96
=> made timecode font bigger

makederiv
added sarah wardrop's noise reduction script as 'transcriptiondisc'
removed mapping issue for mp3 derivatives
=> noise reduction for transcription disc

makederiv
=> switch to bsf:v

makepdf
supersedes https://github.com/mediamicroservices/mm/pull/311
=> removed '-s' flag

README.md, transcription disc scripts/prepare_transcriptionpackage.sh
Repackages audio packages from George Blood
=> Create prepare_transcriptionpackage.sh 

mmfunctions
partially supersedes https://github.com/mediamicroservices/mm/pull/306
=> Check if non first objects files have ordered chapters
